### ISSUE TITLE
What is the current status of this template?

### ISSUE THREAD

**Issue by mgifford** [DISIC/foss-contrib-policy-template#13]
Are people using it?  Will it be reviewed for the next OGP summit?

**Comment by ljoubert** [comment]
Hello, this template is part of the 19th collective action of the Paris declaration from the last OGP Summit: https://paris-declaration.ogpsummit.org/topic/5820e48c2fd812b46ab9facc 
Several engagements are taken regarding local implementation. The whole plan is available: http://www.opengovpartnership.org/sites/default/files/OGP-Summit_PARIS-DECLARATION_EN.pdf

France is in the process of implementing it and we are planning to release it in February 2018.  I will let you know when the public consultation is started.

The template has not evolved since the OGP Summit and part of it might need to be updated. I believe it will be the case with all the collective actions. I should have continued the work with the group, but for the moment I am focusing on the French implementation. I would love to update it or identify what the right sequels would be for the next OGP summit.

**Comment by libremente** [comment]
Hi @ljoubert, since some time passed from the last update, do you have some info regarding this doc? Is it "hosted" under a new umbrella org? Is it in use by any French Public Administration? Thanks for your effort! cc @mgifford

**Comment by mgifford** [comment]
I don't have a sense that this was used at the last one in May. I was certainly watching for similar things.

**Comment by ljoubert** [comment]
Hi, yes the document has now been officialy published by France and is available here:
- https://www.numerique.gouv.fr/publications/politique-logiciel-libre/
- https://github.com/DISIC/politique-de-contribution-open-source

**Comment by libremente** [comment]
Thanks @ljoubert! 👍

**Comment by ljoubert** [comment]
At the international level, I did not manage to transfer this template to a new umbrella organization and the group did not gather to update the document so far.

**Comment by mgifford** [comment]
Nice to see reference to the Government of Canada's Open Government White Paper https://github.com/canada-ca/Open_First_Whitepaper

I think the plan is to have that officially published soon. The writing is essentially done.

**Comment by bzg** [comment]
@ljoubert Can I close this issue and archive the repository? It will be still readable for further reference, if needed, but we should advertize it is not actively maintained anymore.

**Comment by ljoubert** [comment]
Hello, yes of course

**Comment by bzg** [comment]
OK, archiving now, thanks!
